### PR TITLE
Update for 1.11.2

### PR DESCRIPTION
**Pull request by queengooborg**
Title says it all, update CodeChickenCore for 1.11.2!

### CODE REVIEW

**Comment by covers1624** [comment]
No. CCC is dead in 1.11 and has all been merged in to CCL.

**Comment by queengooborg** [comment]
It is?  Hmm, updating the many mods I have may prove more challenging in that case...  I'm unable to look at the source for both CCC and CCL right now, so this might be a stupid question, but have all (or most of) the methods in CCC been incorporated in CCL?

**Comment by covers1624** [comment]
Literally everything except CCUpdateChecker and the deobfuscator has been moved over, same class names. Just delete your imports and have your IDE suggest them.

**Comment by queengooborg** [comment]
Noted, and will migrate all imports over to CCL from now on.  🙂

**Pull request closed without merging**
