### PR TITLE
Add deprecation note based upon issue #19

### PR DESCRIPTION
**Pull request by queengooborg**
If I wasn't told that CCC was deprecated via the comment on my pull request for it's updates, I wouldn't have known -- hopefully this helps others as well!

### CODE REVIEW

**Comment by covers1624** [comment]
I would prefer something like "As of 1.11 CodeChickenCore is dead. CodeChickenLib has swallowed all of CCC's stuff. Please use that instead." or something. The use of deprecated makes it seem like it updated but don't use it if you know what i mean.

**Comment by queengooborg** [comment]
Of course, you're the boss.  ;) I just wrote a quick little thing to get a general idea down ~~and it's totally not 5:00 in the morning here~~ and leave it up for changes however seen fit.  Lemme modify it real quick, and...

**Comment by covers1624** [comment]
Heh, all good, Was up from 3pm thursday to 6am friday working on NEI..

**Comment by covers1624** [comment]
All in all, your initial wording seems about right, maybe replace deprecated with dead.

**Comment by covers1624** [comment]
Nice, want to jump on discord as it would be easier to explain my next change :P https://discord.gg/9nr3qyC

**Comment by queengooborg** [comment]
...done!  Now that you mention it, "dead" is definitely a better way to describe CCC.  X3

As for NEI, yeah, that would definitely do it!  It's those moments when you get into a project as well, and want to finish it as soon as possible.  :P I feel you there!

**Comment by queengooborg** [comment]
Oh sure!  Lemme hop onto my laptop and I shall join right away.  ;)

**Pull request merged**
